<?php
/**
 * Created by PhpStorm.
 * User: yf
 * Date: 2017/2/1
 * Time: 上午12:23
 */

namespace TT\Core\Component;

use Phalcon\DI\FactoryDefault as PhalconDi;

class Di extends PhalconDi
{
    /*
     * 借以实现IOC注入
     */
    protected static $instance;
    static function getInstance(){
        if(!isset(self::$instance)){
            self::$instance = new static();
        }
        return self::$instance;
    }

    public function get($name, $parameters = null)
    {
        try{
            $di = parent::get($name, $parameters); // TODO: Change the autogenerated stub
        } catch (\Phalcon\Exception $e) {
            $di = false;
        }
        return $di;
    }
}